SELECT
  UL.IP_OPERACION,
  UL.USUARIO_OS,
  UL.OPERACION,
  UL.GRP_PRIV,
  UL.FECHA_OPERACION
FROM
  EXTRANET.USUARIO_LOG UL
WHERE
  UL.CODUSUARIO = '{0}'
  AND
  UL.FECHA_OPERACION >= TRUNC(SYSDATE) -1
ORDER BY
  UL.FECHA_OPERACION DESC